name: Deployment On stage Environment

on:
  push:
    branches:
      - 'stage'
jobs:
  deploy:
    name: Deploy for backend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: SSH To stage server
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.SSH_HOST }}
          USER_NAME: ${{ secrets.USER_NAME }}

        run: |
          echo "$PRIVATE_KEY" > private_key
          chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          ./.deployemnt-backend.sh'
